name: "Actions Slack Notification"
description: "Actions to notify slack individual users"
author: "nozomi nishinohara"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "bell"
  color: "yellow"
inputs:
  key:
    description: "Slack app OAuth token"
    required: true
  color:
    description: "Attachments Slack color (default: good)"
    default: good
    required: false
  title:
    description: "Slack title field"
    required: false
    default: "Actions event notification"
  message:
    description: "Slack text field"
    required: false
    default: "Actions event"
  author_icon:
    description: "Author icon URL (default: github.event.sender.avatar_url)"
    required: false
    default: ${{ github.event.sender.avatar_url }}
  fields:
    description: 'Attachments fields as an array object string (e.g. ''[{"title": "test", "value": "test value"}]'')'
    required: false
  debug:
    description: "Print payload if set to 'Y'"
    required: false
